[2025-04-10T02:36:16.460+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_data manual__2025-04-10T02:36:06.586444+00:00 [queued]>
[2025-04-10T02:36:16.472+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_data manual__2025-04-10T02:36:06.586444+00:00 [queued]>
[2025-04-10T02:36:16.472+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-10T02:36:16.519+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2025-04-10 02:36:06.586444+00:00
[2025-04-10T02:36:16.527+0000] {standard_task_runner.py:57} INFO - Started process 257 to run task
[2025-04-10T02:36:16.530+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_data', 'manual__2025-04-10T02:36:06.586444+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpfzkre8wq']
[2025-04-10T02:36:16.532+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask load_data
[2025-04-10T02:36:16.618+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_pipeline.load_data manual__2025-04-10T02:36:06.586444+00:00 [running]> on host 90f408b2c6ca
[2025-04-10T02:36:16.780+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T02:36:06.586444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T02:36:06.586444+00:00'
[2025-04-10T02:36:33.962+0000] {logging_mixin.py:151} INFO - Datos cargados exitosamente en la tabla 'tracks'
[2025-04-10T02:36:33.967+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-10T02:36:33.980+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_data, execution_date=20250410T023606, start_date=20250410T023616, end_date=20250410T023633
[2025-04-10T02:36:34.155+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-10T02:36:34.176+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
